### ISSUE TITLE
content() call returns unpublished items

### ISSUE THREAD

**Issue by falbukrek** [rstudio/connectwidgets#1]
The call to content returns items that are unpublished:

![image](https://user-images.githubusercontent.com/1898940/112996762-757a1d80-913a-11eb-85cf-fcebccdaf96a.png)

And here is what you get when you retrieve content and put it into the table:

![image](https://user-images.githubusercontent.com/1898940/112997064-c5f17b00-913a-11eb-99ba-b09340911a40.png)

If you click "achiever_analysis" you get a 404.

**Comment by Lytol** [comment]
I think there is still a use-case where publishers will want to include unpublished content (i.e. an auditing dashboard of failed content).  My instinct is to allow an option to include/exclude in `content()`. For example:

- `content(..., unpublished = TRUE)` - Do not include unpublished content items by default, but you can opt-in

I think there's also a case that `unpublished` should be included by default, and only excluded explicitly.  Thoughts?

**Comment by falbukrek** [comment]
I ran into this issue with the example Rmd template + radixu again today. I think the default should exclude unpublished content.  The notion that rscpages shows content that you can't actually find via the connect UI feels wrong.
