### ISSUE TITLE
Bulk upload/change of content image

### ISSUE THREAD

**Issue by jthomasmock** [rstudio/connectwidgets#43]
Would love to have functionality within the package to programatically set the content image on RSC and thus the display image for all subsequent views via `connectwidgets`.

For example, if I have 100 pieces of content, I could use RStudio Connect's API to change many pieces of content at once, and then `connectwidgets` will be able to respect those changes in the various views.

**Comment by Lytol** [comment]
`connectwidgets` is unlikely to provide any advanced API client functionality, including setting the content images.  This feels more appropriate for `connectapi`, and `connectwidgets` will already use content images (so updates will *just work*).
