### ISSUE TITLE
Inconsistencies between rscpages and connectapi

### ISSUE THREAD

**Issue by kmasiello** [rstudio/connectwidgets#5]
Between rscpages and connectapi, the content() function behaves differently. This should be consistent for user experience. 

Also for consistency, column names and columns returned should be consistent between the two packages.

**Comment by Lytol** [comment]
The long-term goal is to replace the built-in API client with `connectapi`, but we didn't want to hitch our wagons together while there was uncertainty around `connectapi` and CRAN.  We likely won't fix until we are able to use `connectapi` as our client in its entirety.
