### ISSUE TITLE
How to publish landing page making RSC API calls?

### ISSUE THREAD

**Issue by paddytobias** [rstudio/connectwidgets#62]
Hi, 

I'm running into a problem publishing a landing page with "Publish document with source code" to our RStudio Connect because the landing page is making API calls to the RSConnect server. It seems like making an API call to the RSConnect server *from within* the server causes an error

![image](https://user-images.githubusercontent.com/29882604/144353703-5f662a10-ebaf-433a-a057-5a0d8496e085.png)

Is there anyway around this or can you only publish static landing pages?

**Comment by paddytobias** [comment]
Just found the error message in our log: "Peer's Certificate issuer is not recognized"

**Comment by atheriel** [comment]
What are you using to make the API calls?

**Comment by aronatkins** [comment]
@atheriel - that error message is from here:

https://github.com/rstudio/connectwidgets/blob/ea415784cb240de3e3ceea5fdfaa3929e1345099/R/connect.R#L71-L82

That code attempts to validate that the connectwidgets package can interact with RStudio Connect ahead of any API calls by the user. It may indicate that the server running Connect is unable to communicate with its configured public address (the `Server.Address` setting).

**Comment by atheriel** [comment]
I see that the corresponding `httr` call is [here](https://github.com/rstudio/connectwidgets/blob/ea415784cb240de3e3ceea5fdfaa3929e1345099/R/connect.R#L35). It doesn't seem to expose the ability to ignore cert errors at the moment, but you can set this globally before making the call with

```r
httr::set_config(config(ssl_verifypeer = 0L))
```

**Comment by paddytobias** [comment]
That did the job! Thanks heaps
