### ISSUE TITLE
Misleading error message from `compareVersion`

### ISSUE THREAD

**Issue by paddytobias** [rstudio/connectwidgets#63]
Hi, 

We were running into an issue on our landing pages that was telling us that our RSC server wasn't up to date, despite us running the latest version (2021.12)

![image](https://user-images.githubusercontent.com/29882604/146256038-76ad766e-eb6d-4cfa-9471-7827f3cb296c.png)

After somedebugging, we realised the issue was that the version number was being hidden by the server as per here: https://docs.rstudio.com/connect/admin/appendix/configuration/#Server.HideVersion

Wondering, does the version number comparison need to be a hard check, i.e., error if the comparison fails ? Should it still run if the version is hidden? 

If it should fail, then can we update the error message if there is no version number coming through

https://github.com/rstudio/connectwidgets/blob/8282758bb32bf8520c5fd681028f791b56ef7850/R/connect.R#L84-L92

**Comment by aronatkins** [comment]
@paddytobias, would you mind trying the latest version of the package? The lack of a server version is no longer an error.

You'll need to install from GitHub:

```r
remotes::install_github("rstudio/connectwidgets")
```
