### ISSUE TITLE
custom landing page

### ISSUE THREAD

**Issue by rwaaijman** [rstudio/connectwidgets#95]
We are using a landing page for all our apps. We would like to create our own styling, for example create our own cards, with title of app on top, no owner in title, etc.

Is that possible? and do you have an example? (we would like to keep the image that was uploaded with the app in posit connect)

Furthermore I created this in quarto, but this report needs to be updated (in our case we scheduled this every 15 minutes).
But I rather have the newest content() data available when opening the landing page. Would this be possible (for example using shiny)?

**Comment by Lytol** [comment]
If you're looking to create a fully customized page (especially with live updating as you mentioned), you're probably better off using a web application framework (like shiny) alongside the Posit Connect API (see [API docs](https://docs.posit.co/connect/api/) or [connectapi](https://github.com/rstudio/connectapi)).  `connectwidgets` is really best suited, at least in its current form, as an opinionated, turnkey solution.

I'm going to close for now, but I'll reopen if things change.
